server:
  port: 8082
  tomcat:
    accesslog:
      enabled: true
      directory: ${user.dir}/logs
      pattern: combined
      prefix: request
      file-date-format: -yyyy-MM-dd
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/universitydb
    username: postgres
    password: Service1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true